language: cpp

sudo: enabled
dist: bionic
      
env:
  global:
  - LANG="en_US.UTF-8"

branches:
  only:
  - master
  - coverage

matrix:
  include:

    - name: macOS clang 
      os: osx
      osx_image: xcode10.2
      compiler: clang

    - name: Linux clang
      os: linux
      env: COMPILER=clang++-5.0
      
    - name: Linux gcc + Coverage
      os: linux
      env: COMPILER=c++ COVERAGE=ON

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
      brew update
      brew cask uninstall --force oclint
      ./install-macos-deps.sh
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt install -y clang++-5.0 libboost-system-dev libboost-serialization-dev libboost-thread-dev libgtk2.0-dev libcairo2-dev libbdd-dev; fi
    
script:
  - CMAKE_ARGS="-DCMAKE_CXX_COMPILER=$COMPILER"
  - if [[ -n "$COVERAGE" ]]; then CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_BUILD_TYPE=Debug"; fi
  - cmake . $CMAKE_ARGS
  - make tests
  - make test

after_success:
  - |
    if [[ -n "$COVERAGE" ]]; then
      lcov --directory . --capture --output-file coverage.info
      lcov --remove coverage.info '/usr/*' --output-file coverage.info
      lcov --list coverage.info
      bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
    fi