language: cpp

sudo: enabled

branches:
  only:
  - master
  - coverage

matrix:
  include:

    - name: macOS clang 
      os: osx
      compiler: clang

    - name: Linux clang
      os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: CXX=clang++-5.0

    - name: Linux gcc
      os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: CXX=g++-7 COVERAGE=ON

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall --force oclint; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install-macos-deps.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get install -y lcov libboost-system-dev libboost-serialization-dev libboost-thread-dev libgtk2.0-dev libcairo2-dev libbdd-dev;
      gem install coveralls-lcov;
    fi
    
script: 
  - mkdir build
  - cd build
  - if [ -n "$COVERAGE" ]; then cmake .. -DCMAKE_BUILD_TYPE=Debug; else cmake ..; fi
  - make
  - if [ -n "$COVERAGE" ]; then make lcov_coverage; else make test; fi
  
after_success:
  - if [ -n "$COVERAGE" ]; then 
      lcov --compat-libtool --directory . --capture --rc lcov_branch_coverage=1 --output-file coverage.info;
      coveralls-lcov coverage.info;
    fi
