language: cpp

sudo: enabled
dist: trusty
      
env:
  global:
  - LANG="en_US.UTF-8"

branches:
  only:
  - master
  - coverage
  - docker

matrix:
  include:

    - name: macOS clang 
      os: osx
      compiler: clang

    - name: Linux clang
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: MATRIX_EVAL="CXX=clang++-5.0"
      
    - name: Docker
      os: linux
      compiler: gcc
      services:
        - docker
      env: DOCKER=ubuntu:latest

    - name: Linux gcc
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: CXX=g++-7 COVERAGE=ON

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew cask uninstall --force oclint; ./install-macos-deps.sh; fi
  - eval "${MATRIX_EVAL}" 
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [ -n "$DOCKER" ]; then 
        docker pull $DOCKER
        containerid=$(docker run --detach --tty --volume="$PWD":/ariadne --workdir=/ariadne $DOCKER)
        DOCKER_RUN="docker exec --tty $containerid"
        $DOCKER_RUN sh -c 'apt update'
        $DOCKER_RUN sh -c 'apt install -y curl cmake'
        $DOCKER_RUN sh -c 'apt install -y libboost-system-dev libboost-serialization-dev libboost-thread-dev libgtk2.0-dev libcairo2-dev libbdd-dev'   
      else 
        sudo apt-get install -y libboost-system-dev libboost-serialization-dev libboost-thread-dev libgtk2.0-dev libcairo2-dev libbdd-dev
      fi
    fi
    
script: 
  - mkdir build
  - cd build
  - |
    if [ -n "$COVERAGE" ]; then 
      if [ -n "$DOCKER" ]; then
        $DOCKER_RUN sh -c 'cmake .. -DCMAKE_BUILD_TYPE=Debug'
      else
        cmake .. -DCMAKE_BUILD_TYPE=Debug
      fi 
    else 
      if [ -n "$DOCKER" ]; then 
        $DOCKER_RUN sh -c 'cmake ..'
      else
        cmake ..
      fi
    fi
  - |
    if [ -n "$DOCKER" ]; then 
      $DOCKER_RUN sh -c 'make tests'
      $DOCKER_RUN sh -c 'make test'
    else
      make tests
      make test
    fi 
after_success:
  - |
    if [ -n "$COVERAGE" ]; then
      if [ -n "$DOCKER" ]; then
        $DOCKER_RUN sh -c 'bash <(curl -s https://codecov.io/bash)'
      else
        bash <(curl -s https://codecov.io/bash)
    fi
