language: cpp

sudo: enabled

env:
  global:
  - LANG="en_US.UTF-8"

branches:
  only:
  - master
  - coverage

matrix:
  include:

    - name: macOS clang 
      os: osx
      compiler: clang

    - name: Linux clang
      os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: MATRIX_EVAL="CXX=clang++-5.0"

    - name: Linux gcc
      os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: CXX=g++-7 COVERAGE=ON

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew cask uninstall --force oclint; ./install-macos-deps.sh; fi
  - eval "${MATRIX_EVAL}" 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get install -y lcov libboost-system-dev libboost-serialization-dev libboost-thread-dev libgtk2.0-dev libcairo2-dev libbdd-dev;
      gem install coveralls-lcov;
    fi
    
script: 
  - mkdir build
  - cd build
  - if [ -n "$COVERAGE" ]; then cmake .. -DCMAKE_BUILD_TYPE=Debug; else cmake ..; fi
  - make tests
  - if [ -n "$COVERAGE" ]; then make test; else make test; fi
# mv lcov_coverage.info.cleaned coverage.info;
# lcov --list coverage.info;
after_success:
  - if [ -n "$COVERAGE" ]; then
      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports";
    fi
